2025-09-26 16:24:35,128 INFO: Loaded 2 urls from url.txt
2025-09-26 16:24:35,128 INFO: Selenium is available: using Selenium-based rendering
2025-09-26 16:24:35,129 INFO: [selenium] Scanning: https://web.facebook.com
2025-09-26 16:24:35,129 INFO: ====== WebDriver manager ======
2025-09-26 16:24:35,130 INFO: [selenium] Scanning: http://vulnweb.com
2025-09-26 16:24:35,130 INFO: ====== WebDriver manager ======
2025-09-26 16:24:35,150 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:24:35,151 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:24:35,467 INFO: About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
2025-09-26 16:24:35,479 INFO: About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
2025-09-26 16:24:35,784 INFO: Driver downloading response is 200
2025-09-26 16:24:35,798 INFO: Driver downloading response is 200
2025-09-26 16:24:45,986 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:24:45,989 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:24:46,325 ERROR: [selenium] Error scanning http://vulnweb.com: tuple index out of range
Traceback (most recent call last):
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/webdriver_manager/core/file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/zipfile/__init__.py", line 1788, in extractall
    self._extract_member(zipinfo, path, pwd)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/zipfile/__init__.py", line 1850, in _extract_member
    shutil.copyfileobj(source, target)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/shutil.py", line 203, in copyfileobj
    while buf := fsrc_read(length):
                 ~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/zipfile/__init__.py", line 1015, in read
    data = self._read1(n)
  File "/usr/lib/python3.13/zipfile/__init__.py", line 1083, in _read1
    data += self._read2(n - len(data))
            ~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/zipfile/__init__.py", line 1118, in _read2
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Desktop/STUDY_PROGRM/tools/ctf_scanner.py", line 137, in scan_single_url_selenium
    driver = make_driver(show_browser=show_browser)
  File "/home/kali/Desktop/STUDY_PROGRM/tools/ctf_scanner.py", line 84, in make_driver
    service = Service(ChromeDriverManager().install())
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/webdriver_manager/chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/webdriver_manager/core/manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/webdriver_manager/core/driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/webdriver_manager/core/driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/webdriver_manager/core/file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/webdriver_manager/core/file_manager.py", line 67, in __extract_zip
    if e.args[0] not in [26, 13] and e.args[1] not in [
       ~~~~~~^^^
IndexError: tuple index out of range
2025-09-26 16:24:46,479 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:24:46,778 INFO: Driver has been saved in cache [/home/kali/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
2025-09-26 16:24:47,226 ERROR: [selenium] Error scanning https://web.facebook.com: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 140.0.7339.185 with binary path /usr/bin/chromium; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x5644badf44e3 <unknown>
#1 0x5644bab23c76 <unknown>
#2 0x5644bab5104a <unknown>
#3 0x5644bab4c4a1 <unknown>
#4 0x5644bab49029 <unknown>
#5 0x5644bab87ccc <unknown>
#6 0x5644bab8747f <unknown>
#7 0x5644bab7ede3 <unknown>
#8 0x5644bab542dd <unknown>
#9 0x5644bab5534e <unknown>
#10 0x5644badb43e4 <unknown>
#11 0x5644badb83d7 <unknown>
#12 0x5644badc2b20 <unknown>
#13 0x5644badb9023 <unknown>
#14 0x5644bad871aa <unknown>
#15 0x5644baddd6b8 <unknown>
#16 0x5644baddd847 <unknown>
#17 0x5644baded243 <unknown>
#18 0x7f848c46ab7b <unknown>
Traceback (most recent call last):
  File "/home/kali/Desktop/STUDY_PROGRM/tools/ctf_scanner.py", line 137, in scan_single_url_selenium
    driver = make_driver(show_browser=show_browser)
  File "/home/kali/Desktop/STUDY_PROGRM/tools/ctf_scanner.py", line 85, in make_driver
    driver = webdriver.Chrome(service=service, options=opts)
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        browser_name=DesiredCapabilities.CHROME["browserName"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        keep_alive=keep_alive,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 263, in __init__
    self.start_session(capabilities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 366, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 458, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 140.0.7339.185 with binary path /usr/bin/chromium; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x5644badf44e3 <unknown>
#1 0x5644bab23c76 <unknown>
#2 0x5644bab5104a <unknown>
#3 0x5644bab4c4a1 <unknown>
#4 0x5644bab49029 <unknown>
#5 0x5644bab87ccc <unknown>
#6 0x5644bab8747f <unknown>
#7 0x5644bab7ede3 <unknown>
#8 0x5644bab542dd <unknown>
#9 0x5644bab5534e <unknown>
#10 0x5644badb43e4 <unknown>
#11 0x5644badb83d7 <unknown>
#12 0x5644badc2b20 <unknown>
#13 0x5644badb9023 <unknown>
#14 0x5644bad871aa <unknown>
#15 0x5644baddd6b8 <unknown>
#16 0x5644baddd847 <unknown>
#17 0x5644baded243 <unknown>
#18 0x7f848c46ab7b <unknown>

2025-09-26 16:24:47,231 INFO: Saved JSON -> khoba_output/results.json CSV -> khoba_output/results.csv HTMLs -> /home/kali/Desktop/STUDY_PROGRM/tools/khoba_output/html
2025-09-26 16:24:55,302 INFO: Loaded 2 urls from url.txt
2025-09-26 16:24:55,302 INFO: Selenium is available: using Selenium-based rendering
2025-09-26 16:24:55,303 INFO: [selenium] Scanning: https://web.facebook.com
2025-09-26 16:24:55,303 INFO: [selenium] Scanning: http://vulnweb.com
2025-09-26 16:24:55,303 INFO: ====== WebDriver manager ======
2025-09-26 16:24:55,303 INFO: ====== WebDriver manager ======
2025-09-26 16:24:55,321 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:24:55,325 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:24:55,705 INFO: About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
2025-09-26 16:24:55,709 INFO: About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
2025-09-26 16:24:55,995 INFO: Driver downloading response is 200
2025-09-26 16:24:55,996 INFO: Driver downloading response is 200
2025-09-26 16:25:01,844 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:25:02,381 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:25:02,737 INFO: Driver has been saved in cache [/home/kali/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
2025-09-26 16:25:02,955 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:25:03,179 ERROR: [selenium] Error scanning http://vulnweb.com: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 140.0.7339.185 with binary path /usr/bin/chromium; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x55d68a4294e3 <unknown>
#1 0x55d68a158c76 <unknown>
#2 0x55d68a18604a <unknown>
#3 0x55d68a1814a1 <unknown>
#4 0x55d68a17e029 <unknown>
#5 0x55d68a1bcccc <unknown>
#6 0x55d68a1bc47f <unknown>
#7 0x55d68a1b3de3 <unknown>
#8 0x55d68a1892dd <unknown>
#9 0x55d68a18a34e <unknown>
#10 0x55d68a3e93e4 <unknown>
#11 0x55d68a3ed3d7 <unknown>
#12 0x55d68a3f7b20 <unknown>
#13 0x55d68a3ee023 <unknown>
#14 0x55d68a3bc1aa <unknown>
#15 0x55d68a4126b8 <unknown>
#16 0x55d68a412847 <unknown>
#17 0x55d68a422243 <unknown>
#18 0x7f4e3ec0cb7b <unknown>
Traceback (most recent call last):
  File "/home/kali/Desktop/STUDY_PROGRM/tools/ctf_scanner.py", line 137, in scan_single_url_selenium
    driver = make_driver(show_browser=show_browser)
  File "/home/kali/Desktop/STUDY_PROGRM/tools/ctf_scanner.py", line 85, in make_driver
    driver = webdriver.Chrome(service=service, options=opts)
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        browser_name=DesiredCapabilities.CHROME["browserName"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        keep_alive=keep_alive,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 263, in __init__
    self.start_session(capabilities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 366, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 458, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 140.0.7339.185 with binary path /usr/bin/chromium; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x55d68a4294e3 <unknown>
#1 0x55d68a158c76 <unknown>
#2 0x55d68a18604a <unknown>
#3 0x55d68a1814a1 <unknown>
#4 0x55d68a17e029 <unknown>
#5 0x55d68a1bcccc <unknown>
#6 0x55d68a1bc47f <unknown>
#7 0x55d68a1b3de3 <unknown>
#8 0x55d68a1892dd <unknown>
#9 0x55d68a18a34e <unknown>
#10 0x55d68a3e93e4 <unknown>
#11 0x55d68a3ed3d7 <unknown>
#12 0x55d68a3f7b20 <unknown>
#13 0x55d68a3ee023 <unknown>
#14 0x55d68a3bc1aa <unknown>
#15 0x55d68a4126b8 <unknown>
#16 0x55d68a412847 <unknown>
#17 0x55d68a422243 <unknown>
#18 0x7f4e3ec0cb7b <unknown>

2025-09-26 16:25:03,409 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:25:03,718 INFO: Driver has been saved in cache [/home/kali/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
2025-09-26 16:25:04,148 ERROR: [selenium] Error scanning https://web.facebook.com: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 140.0.7339.185 with binary path /usr/bin/chromium; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x55e5388014e3 <unknown>
#1 0x55e538530c76 <unknown>
#2 0x55e53855e04a <unknown>
#3 0x55e5385594a1 <unknown>
#4 0x55e538556029 <unknown>
#5 0x55e538594ccc <unknown>
#6 0x55e53859447f <unknown>
#7 0x55e53858bde3 <unknown>
#8 0x55e5385612dd <unknown>
#9 0x55e53856234e <unknown>
#10 0x55e5387c13e4 <unknown>
#11 0x55e5387c53d7 <unknown>
#12 0x55e5387cfb20 <unknown>
#13 0x55e5387c6023 <unknown>
#14 0x55e5387941aa <unknown>
#15 0x55e5387ea6b8 <unknown>
#16 0x55e5387ea847 <unknown>
#17 0x55e5387fa243 <unknown>
#18 0x7f4044045b7b <unknown>
Traceback (most recent call last):
  File "/home/kali/Desktop/STUDY_PROGRM/tools/ctf_scanner.py", line 137, in scan_single_url_selenium
    driver = make_driver(show_browser=show_browser)
  File "/home/kali/Desktop/STUDY_PROGRM/tools/ctf_scanner.py", line 85, in make_driver
    driver = webdriver.Chrome(service=service, options=opts)
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        browser_name=DesiredCapabilities.CHROME["browserName"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        keep_alive=keep_alive,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 263, in __init__
    self.start_session(capabilities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 366, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 458, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 140.0.7339.185 with binary path /usr/bin/chromium; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x55e5388014e3 <unknown>
#1 0x55e538530c76 <unknown>
#2 0x55e53855e04a <unknown>
#3 0x55e5385594a1 <unknown>
#4 0x55e538556029 <unknown>
#5 0x55e538594ccc <unknown>
#6 0x55e53859447f <unknown>
#7 0x55e53858bde3 <unknown>
#8 0x55e5385612dd <unknown>
#9 0x55e53856234e <unknown>
#10 0x55e5387c13e4 <unknown>
#11 0x55e5387c53d7 <unknown>
#12 0x55e5387cfb20 <unknown>
#13 0x55e5387c6023 <unknown>
#14 0x55e5387941aa <unknown>
#15 0x55e5387ea6b8 <unknown>
#16 0x55e5387ea847 <unknown>
#17 0x55e5387fa243 <unknown>
#18 0x7f4044045b7b <unknown>

2025-09-26 16:25:04,153 INFO: Saved JSON -> khoba_output/results.json CSV -> khoba_output/results.csv HTMLs -> /home/kali/Desktop/STUDY_PROGRM/tools/khoba_output/html
2025-09-26 16:25:47,990 INFO: Loaded 2 urls from url.txt
2025-09-26 16:25:47,990 INFO: Selenium is available: using Selenium-based rendering
2025-09-26 16:25:47,991 INFO: [selenium] Scanning: https://web.facebook.com
2025-09-26 16:25:47,991 INFO: ====== WebDriver manager ======
2025-09-26 16:25:48,007 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:25:48,314 INFO: About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
2025-09-26 16:25:48,650 INFO: Driver downloading response is 200
2025-09-26 16:25:53,115 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:25:53,617 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:25:53,943 INFO: Driver has been saved in cache [/home/kali/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
2025-09-26 16:25:54,444 ERROR: [selenium] Error scanning https://web.facebook.com: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 140.0.7339.185 with binary path /usr/bin/chromium; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x564a28e5c4e3 <unknown>
#1 0x564a28b8bc76 <unknown>
#2 0x564a28bb904a <unknown>
#3 0x564a28bb44a1 <unknown>
#4 0x564a28bb1029 <unknown>
#5 0x564a28befccc <unknown>
#6 0x564a28bef47f <unknown>
#7 0x564a28be6de3 <unknown>
#8 0x564a28bbc2dd <unknown>
#9 0x564a28bbd34e <unknown>
#10 0x564a28e1c3e4 <unknown>
#11 0x564a28e203d7 <unknown>
#12 0x564a28e2ab20 <unknown>
#13 0x564a28e21023 <unknown>
#14 0x564a28def1aa <unknown>
#15 0x564a28e456b8 <unknown>
#16 0x564a28e45847 <unknown>
#17 0x564a28e55243 <unknown>
#18 0x7f08e5510b7b <unknown>
Traceback (most recent call last):
  File "/home/kali/Desktop/STUDY_PROGRM/tools/ctf_scanner.py", line 137, in scan_single_url_selenium
    driver = make_driver(show_browser=show_browser)
  File "/home/kali/Desktop/STUDY_PROGRM/tools/ctf_scanner.py", line 85, in make_driver
    driver = webdriver.Chrome(service=service, options=opts)
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        browser_name=DesiredCapabilities.CHROME["browserName"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        keep_alive=keep_alive,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 263, in __init__
    self.start_session(capabilities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 366, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 458, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 140.0.7339.185 with binary path /usr/bin/chromium; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x564a28e5c4e3 <unknown>
#1 0x564a28b8bc76 <unknown>
#2 0x564a28bb904a <unknown>
#3 0x564a28bb44a1 <unknown>
#4 0x564a28bb1029 <unknown>
#5 0x564a28befccc <unknown>
#6 0x564a28bef47f <unknown>
#7 0x564a28be6de3 <unknown>
#8 0x564a28bbc2dd <unknown>
#9 0x564a28bbd34e <unknown>
#10 0x564a28e1c3e4 <unknown>
#11 0x564a28e203d7 <unknown>
#12 0x564a28e2ab20 <unknown>
#13 0x564a28e21023 <unknown>
#14 0x564a28def1aa <unknown>
#15 0x564a28e456b8 <unknown>
#16 0x564a28e45847 <unknown>
#17 0x564a28e55243 <unknown>
#18 0x7f08e5510b7b <unknown>

2025-09-26 16:25:54,448 INFO: [selenium] Scanning: http://vulnweb.com
2025-09-26 16:25:54,448 INFO: ====== WebDriver manager ======
2025-09-26 16:25:54,466 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:25:54,764 INFO: About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
2025-09-26 16:25:55,076 INFO: Driver downloading response is 200
2025-09-26 16:26:00,115 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:26:00,559 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:26:00,853 INFO: Driver has been saved in cache [/home/kali/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
2025-09-26 16:26:01,277 ERROR: [selenium] Error scanning http://vulnweb.com: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 140.0.7339.185 with binary path /usr/bin/chromium; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x55c2b31454e3 <unknown>
#1 0x55c2b2e74c76 <unknown>
#2 0x55c2b2ea204a <unknown>
#3 0x55c2b2e9d4a1 <unknown>
#4 0x55c2b2e9a029 <unknown>
#5 0x55c2b2ed8ccc <unknown>
#6 0x55c2b2ed847f <unknown>
#7 0x55c2b2ecfde3 <unknown>
#8 0x55c2b2ea52dd <unknown>
#9 0x55c2b2ea634e <unknown>
#10 0x55c2b31053e4 <unknown>
#11 0x55c2b31093d7 <unknown>
#12 0x55c2b3113b20 <unknown>
#13 0x55c2b310a023 <unknown>
#14 0x55c2b30d81aa <unknown>
#15 0x55c2b312e6b8 <unknown>
#16 0x55c2b312e847 <unknown>
#17 0x55c2b313e243 <unknown>
#18 0x7ff2b03fdb7b <unknown>
Traceback (most recent call last):
  File "/home/kali/Desktop/STUDY_PROGRM/tools/ctf_scanner.py", line 137, in scan_single_url_selenium
    driver = make_driver(show_browser=show_browser)
  File "/home/kali/Desktop/STUDY_PROGRM/tools/ctf_scanner.py", line 85, in make_driver
    driver = webdriver.Chrome(service=service, options=opts)
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        browser_name=DesiredCapabilities.CHROME["browserName"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        keep_alive=keep_alive,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 263, in __init__
    self.start_session(capabilities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 366, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 458, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/kali/selfscript-tools/venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 140.0.7339.185 with binary path /usr/bin/chromium; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x55c2b31454e3 <unknown>
#1 0x55c2b2e74c76 <unknown>
#2 0x55c2b2ea204a <unknown>
#3 0x55c2b2e9d4a1 <unknown>
#4 0x55c2b2e9a029 <unknown>
#5 0x55c2b2ed8ccc <unknown>
#6 0x55c2b2ed847f <unknown>
#7 0x55c2b2ecfde3 <unknown>
#8 0x55c2b2ea52dd <unknown>
#9 0x55c2b2ea634e <unknown>
#10 0x55c2b31053e4 <unknown>
#11 0x55c2b31093d7 <unknown>
#12 0x55c2b3113b20 <unknown>
#13 0x55c2b310a023 <unknown>
#14 0x55c2b30d81aa <unknown>
#15 0x55c2b312e6b8 <unknown>
#16 0x55c2b312e847 <unknown>
#17 0x55c2b313e243 <unknown>
#18 0x7ff2b03fdb7b <unknown>

2025-09-26 16:26:01,282 INFO: Saved JSON -> khoba_output/results.json CSV -> khoba_output/results.csv HTMLs -> /home/kali/Desktop/STUDY_PROGRM/tools/khoba_output/html
2025-09-26 16:28:28,053 INFO: Loaded 2 urls from url.txt
2025-09-26 16:28:28,053 INFO: Selenium not available: using static requests fallback (no JS)
2025-09-26 16:28:28,054 INFO: [requests] Fetching: https://web.facebook.com
2025-09-26 16:28:28,055 INFO: [requests] Fetching: http://vulnweb.com
2025-09-26 16:28:28,650 INFO: [requests] Done: https://web.facebook.com -> tags: 0, attrs: 1
2025-09-26 16:28:28,708 INFO: [requests] Done: http://vulnweb.com -> tags: 0, attrs: 1
2025-09-26 16:28:28,710 INFO: Saved JSON -> khoba_output/results.json CSV -> khoba_output/results.csv HTMLs -> /home/kali/Desktop/STUDY_PROGRM/tools/khoba_output/html
2025-09-26 16:35:13,035 INFO: Loaded 1 urls from url.txt
2025-09-26 16:35:13,035 INFO: ====== WebDriver manager ======
2025-09-26 16:35:13,051 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:35:13,481 INFO: About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
2025-09-26 16:35:13,779 INFO: Driver downloading response is 200
2025-09-26 16:35:17,343 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:35:17,886 INFO: Get LATEST chromedriver version for google-chrome
2025-09-26 16:35:18,178 INFO: Driver has been saved in cache [/home/kali/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
2025-09-26 16:35:18,576 WARNING: Selenium driver check failed: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 140.0.7339.185 with binary path /usr/bin/chromium; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x5587ed8384e3 <unknown>
#1 0x5587ed567c76 <unknown>
#2 0x5587ed59504a <unknown>
#3 0x5587ed5904a1 <unknown>
#4 0x5587ed58d029 <unknown>
#5 0x5587ed5cbccc <unknown>
#6 0x5587ed5cb47f <unknown>
#7 0x5587ed5c2de3 <unknown>
#8 0x5587ed5982dd <unknown>
#9 0x5587ed59934e <unknown>
#10 0x5587ed7f83e4 <unknown>
#11 0x5587ed7fc3d7 <unknown>
#12 0x5587ed806b20 <unknown>
#13 0x5587ed7fd023 <unknown>
#14 0x5587ed7cb1aa <unknown>
#15 0x5587ed8216b8 <unknown>
#16 0x5587ed821847 <unknown>
#17 0x5587ed831243 <unknown>
#18 0x7f70f2b37b7b <unknown>

2025-09-26 16:35:18,576 WARNING: Selenium detected but driver/browser incompatible; falling back to requests (no JS)
2025-09-26 16:35:18,578 INFO: [requests] Fetching: https://hex.tech
2025-09-26 16:35:19,797 INFO: [requests] Done: https://hex.tech -> tags: 1, attrs: 15
2025-09-26 16:35:19,799 INFO: Saved JSON -> khoba_output/results.json CSV -> khoba_output/results.csv HTMLs -> /home/kali/Desktop/STUDY_PROGRM/tools/khoba_output/html
